name: cook_it
description: Cooking is no more a challenge

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/search_button.png
    - assets/images/fridge_button.png
    - assets/images/folder_button.png
    - assets/images/timer.png
    - assets/images/calories.png
    - assets/images/proteins.png
    - assets/images/fats.png
    - assets/FridgeXX.db
    - assets/images/category1.png
    - assets/images/category2.png
    - assets/images/category3.png
    - assets/images/category4.png
    - assets/images/category5.png
    - assets/images/category6.png
    - assets/images/category7.png
    - assets/images/category8.png
    - assets/images/category9.png
    - assets/images/category10.png
    - assets/images/category11.png
    - assets/images/category12.png
    - assets/images/category13.png
    - assets/images/category14.png
    - assets/images/category15.png
    - assets/images/category16.png
    - assets/images/category17.png
    - assets/images/category18.png
    - assets/images/category19.png
    - assets/images/category20.png
    - assets/images/category21.png
    - assets/images/splash.png
    - assets/images/fridge.png
    - assets/images/recipes/recipe_1.jpg
    - assets/images/recipes/recipe_2.jpg
    - assets/images/recipes/recipe_3.jpg
    - assets/images/recipes/recipe_4.jpg
    - assets/images/recipes/recipe_5.jpg
    - assets/images/recipes/recipe_6.jpg
    - assets/images/recipes/recipe_7.jpg
    - assets/images/recipes/recipe_8.jpg
    - assets/images/recipes/recipe_9.jpg
    - assets/images/recipes/recipe_10.jpg
    - assets/images/recipes/recipe_11.jpg
    - assets/images/recipes/recipe_12.jpg
    - assets/images/recipes/recipe_13.jpg
    - assets/images/recipes/recipe_14.jpg
    - assets/images/recipes/recipe_15.jpg
    - assets/images/recipes/recipe_16.jpg
    - assets/images/recipes/recipe_17.jpg
    - assets/images/recipes/recipe_18.jpg
    - assets/images/recipes/recipe_19.jpg
    - assets/images/recipes/recipe_20.jpg
    - assets/images/recipes/recipe_21.jpg
    - assets/images/recipes/recipe_22.jpg
    - assets/images/recipes/recipe_23.jpg
    - assets/images/recipes/recipe_24.jpg
    - assets/images/recipes/recipe_25.jpg
    - assets/images/recipes/recipe_26.jpg
    - assets/images/recipes/recipe_27.jpg
    - assets/images/recipes/recipe_28.jpg
    - assets/images/recipes/recipe_29.jpg
    - assets/images/recipes/recipe_30.jpg
    - assets/images/recipes/recipe_31.jpg
    - assets/images/recipes/recipe_32.jpg
    - assets/images/recipes/recipe_33.jpg
    - assets/images/recipes/recipe_34.jpg
    - assets/images/recipes/recipe_35.jpg
    - assets/images/recipes/recipe_36.jpg
    - assets/images/recipes/recipe_37.jpg
    - assets/images/recipes/recipe_38.jpg
    - assets/images/recipes/recipe_39.jpg
    - assets/images/recipes/recipe_40.jpg
    - assets/images/recipes/recipe_41.jpg
    - assets/images/recipes/recipe_42.jpg
    - assets/images/recipes/recipe_43.jpg
    - assets/images/recipes/recipe_44.jpg
    - assets/images/recipes/recipe_45.jpg
    - assets/images/recipes/recipe_46.jpg
    - assets/images/recipes/recipe_47.jpg
    - assets/images/recipes/recipe_48.jpg
    - assets/images/recipes/recipe_49.jpg
    - assets/images/recipes/recipe_50.jpg
    - assets/images/recipes/recipe_51.jpg
    - assets/images/recipes/recipe_52.jpg
    - assets/images/recipes/recipe_53.jpg
    - assets/images/recipes/recipe_54.jpg
    - assets/images/recipes/recipe_55.jpg
    - assets/images/recipes/recipe_56.jpg
    - assets/images/recipes/recipe_57.jpg
    - assets/images/recipes/recipe_58.jpg
    - assets/images/recipes/recipe_59.jpg
    - assets/images/recipes/recipe_60.jpg
    - assets/images/recipes/recipe_61.jpg
    - assets/images/recipes/recipe_62.jpg
    - assets/images/recipes/recipe_63.jpg
    - assets/images/recipes/recipe_64.jpg
    - assets/images/recipes/recipe_65.jpg
    - assets/images/recipes/recipe_66.jpg
    - assets/images/recipes/recipe_67.jpg
    - assets/images/recipes/recipe_68.jpg
    - assets/images/recipes/recipe_69.jpg
    - assets/images/recipes/recipe_70.jpg
    - assets/images/recipes/recipe_71.jpg
    - assets/images/recipes/recipe_72.jpg
    - assets/images/recipes/recipe_73.jpg
    - assets/images/recipes/recipe_74.jpg
    - assets/images/recipes/recipe_75.jpg
    - assets/images/recipes/recipe_76.jpg
    - assets/images/recipes/recipe_77.jpg
    - assets/images/recipes/recipe_78.jpg
    - assets/images/recipes/recipe_79.jpg
    - assets/images/recipes/recipe_80.jpg
    - assets/images/recipes/recipe_81.jpg
    - assets/images/recipes/recipe_82.jpg
    - assets/images/recipes/recipe_83.jpg
    - assets/images/recipes/recipe_84.jpg
    - assets/images/recipes/recipe_85.jpg
    - assets/images/recipes/recipe_86.jpg
    - assets/images/recipes/recipe_87.jpg
    - assets/images/recipes/recipe_88.jpg
    - assets/images/recipes/recipe_89.jpg
    - assets/images/recipes/recipe_90.jpg
    - assets/images/recipes/recipe_91.jpg
    - assets/images/recipes/recipe_92.jpg
    - assets/images/recipes/recipe_93.jpg
    - assets/images/recipes/recipe_94.jpg
    - assets/images/recipes/recipe_95.jpg
    - assets/images/recipes/recipe_96.jpg
    - assets/images/recipes/recipe_97.jpg
    - assets/images/recipes/recipe_98.jpg
    - assets/images/recipes/recipe_99.jpg
    - assets/images/recipes/recipe_100.jpg
    - assets/images/recipes/recipe_101.jpg
    - assets/images/recipes/recipe_102.jpg
    - assets/images/recipes/recipe_103.jpg
    - assets/images/recipes/recipe_104.jpg
    - assets/images/recipes/recipe_105.jpg
    - assets/images/recipes/recipe_106.jpg
    - assets/images/recipes/recipe_107.jpg
    - assets/images/recipes/recipe_108.jpg
    - assets/images/recipes/recipe_109.jpg
    - assets/images/recipes/recipe_110.jpg
    - assets/images/recipes/recipe_111.jpg
    - assets/images/recipes/recipe_112.jpg
    - assets/images/recipes/recipe_113.jpg
    - assets/images/recipes/recipe_114.jpg
    - assets/images/recipes/recipe_115.jpg
    - assets/images/recipes/recipe_116.jpg
    - assets/images/recipes/recipe_117.jpg
    - assets/images/recipes/recipe_118.jpg
    - assets/images/recipes/recipe_119.jpg
    - assets/images/recipes/recipe_120.jpg
    - assets/images/recipes/recipe_121.jpg
    - assets/images/recipes/recipe_122.jpg
    - assets/images/recipes/recipe_123.jpg
    - assets/images/recipes/recipe_124.jpg
    - assets/images/recipes/recipe_125.jpg
    - assets/images/recipes/recipe_126.jpg
    - assets/images/recipes/recipe_127.jpg
    - assets/images/recipes/recipe_128.jpg
    - assets/images/recipes/recipe_129.jpg
    - assets/images/recipes/recipe_130.jpg
    - assets/images/recipes/recipe_131.jpg
    - assets/images/recipes/recipe_132.jpg
    - assets/images/recipes/recipe_133.jpg
    - assets/images/recipes/recipe_134.jpg
    - assets/images/recipes/recipe_135.jpg
    - assets/images/recipes/recipe_136.jpg
    - assets/images/recipes/recipe_137.jpg
    - assets/images/recipes/recipe_138.jpg
    - assets/images/recipes/recipe_139.jpg
    - assets/images/recipes/recipe_140.jpg
    - assets/images/recipes/recipe_141.jpg
    - assets/images/recipes/recipe_142.jpg
    - assets/images/recipes/recipe_143.jpg
    - assets/images/recipes/recipe_144.jpg
    - assets/images/recipes/recipe_145.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfort
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
